### ISSUE TITLE
can't open kinect v2, how to solve this problem???

### ISSUE THREAD

**Issue by wangwenfeng0** [ofTheo/ofxKinectV2#22]
The error is :   Driver file operation error. DeviceIoControl failed (Cannot create a file when that file already exists.  Error code = 183)
my PC is windows 10,  openframework is 0.9.3, and VS is 2015,
 if someone know this problem, please tell me,thank you very much.

**Comment by ofTheo** [comment]
It should work on Windows but needs some documentation. Closing this in favor of #38
