### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TheInnerParty** [ofTheo/ofxKinectV2#26]
Hi, thanks for making this great add-on! I noticed that this project, while public, doesn't have an open source license attached to it, preventing use, contributions, derivative work, etc. Is this intentional, and is it okay if we use this code as part of an open source project? Thank you!

**Comment by ofTheo** [comment]
Sure thing. License is MIT same as OF: https://github.com/openframeworks/openFrameworks/blob/master/LICENSE.md
