### ISSUE TITLE
Point Cloud using ofxKinectV2

### ISSUE THREAD

**Issue by eulphean** [ofTheo/ofxKinectV2#33]
Hey, is it possible to generate a point cloud using the APIs of this addon?

**Comment by bakercp** [comment]
See example at https://github.com/bakercp/ofxKinectV2 :)

**Comment by iamsile** [comment]
Hi, @bakercp When I used your point cloud case from your fork, I find some issues in it.

"Use of undeclared identifier 'glm'" in your ofxKinectV2.h

Look forward to your reply!

Thanks

**Comment by bakercp** [comment]
It only works with the master branch of OF. It isn't compatible with 0.9.8

**Comment by bakercp** [comment]
@ofTheo I think this is probably resolved.  CB

**Comment by ofTheo** [comment]
Thanks @bakercp ! 
Appreciate all the new features in that PR 🙏
