### ISSUE TITLE
On quitting: application does not quit and has to be "Force quit", warning: application left some devices open

### ISSUE THREAD

**Issue by eighteight** [ofTheo/ofxKinectV2#5]
See subj. Kinect has to be powercycled to be usable again. 

The complete (from start to quit) follows:

Using libusbx v1.0.17.10852

Trying to open device 045E:02D8...
             speed: 5000 Mbit/s (USB SuperSpeed)
active configuration: 1, err: 0
Claiming interface 0...
libusbx: info [darwin_claim_interface] no interface found; setting configuration: 1

Claiming interface 1...
running kinect...
Control transfer 1 - set isoch delay
Control transfer 2 - set sel u1/u2

Setting interface alt setting...
Setting stream status: Disable
Control transfer 3 - enable u1
Control transfer 4 - enable u2
Control transfer 5 - set feature 768
Setting sensor status: Disable
Kinect init done

iso max_packet_size: 33792
             speed: 5000 Mbit/s (USB SuperSpeed)
running kinect...
Setting sensor status: Enable

===

Cmd seq 0 func 0x02 (0)
Cmd sent, 20 bytes sent
Cmd response seq 0 func 0x02 (0)
Cmd response success, 512 bytes received
Received cmd data 0x02 (0), length: 512
Cmd response seq 0 func 0x02 (0)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x02 (0)
dumping 512 bytes of raw data from command KCMD_READ_DATA1: 
0x0000:  03 00 02 00 48 0f 00 00 00 00 00 00 00 00 00 00     ....H...........
0x0010:  03 00 02 00 48 0f 00 00 00 00 00 00 00 00 00 00     ....H...........
0x0020:  03 00 02 00 48 0f 00 00 00 00 00 00 00 00 00 00     ....H...........
0x0030:  03 00 02 00 48 0f 00 00 00 00 00 00 00 00 00 00     ....H...........
0x0040:  03 00 02 00 48 0f 00 00 00 00 00 00 00 00 00 00     ....H...........
0x0050:  03 00 02 00 48 0f 00 00 00 00 00 00 00 00 00 00     ....H...........
0x0060:  03 00 02 00 48 0f 00 00 00 00 00 00 00 00 00 00     ....H...........
0x0070:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0080:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0090:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x00a0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x00b0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x00c0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x00d0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x00e0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x00f0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0100:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0110:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0120:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0130:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0140:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0150:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0160:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0170:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0180:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0190:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x01a0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x01b0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x01c0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x01d0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x01e0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x01f0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................

===

Cmd seq 1 func 0x14 (0)
Cmd sent, 20 bytes sent
Cmd response seq 1 func 0x14 (0)
Cmd response success, 92 bytes received
Received cmd data 0x14 (0), length: 92
Cmd response seq 1 func 0x14 (0)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x14 (0)
dumping 92 bytes of raw data from command KCMD_READ_VERSIONS: 
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41     ............C..A
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0020:  0a 21 33 55 c2 00 17 20 00 08 00 00 10 00 00 00     .!3U... ........
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00     ................
0x0040:  31 33 00 00 00 04 13 04 47 4d 43 38 30 34 2e 31     13......GMC804.1
0x0050:  58 00 00 00 00 00 00 00 00 00 00 00                 X...........

===

Cmd seq 2 func 0x22 (0x1)
Cmd sent, 24 bytes sent
Cmd response seq 2 func 0x22 (0x1)
Cmd response success, 128 bytes received
Received cmd data 0x22 (0x1), length: 128
Cmd response seq 2 func 0x22 (0x1)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x22 (0x1)
dumping 128 bytes of raw data from command KCMD_READ_DATA_PAGE 0x01: 
0x0000:  35 00 30 00 31 00 35 00 32 00 33 00 35 00 34 00     5.0.1.5.2.3.5.4.
0x0010:  31 00 39 00 34 00 32 00 00 00 00 00 00 00 00 00     1.9.4.2.........
0x0020:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0030:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0040:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0050:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0060:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0070:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................

===

Cmd seq 3 func 0x22 (0x3)
Cmd sent, 24 bytes sent
Cmd response seq 3 func 0x22 (0x3)
Cmd response success, 92 bytes received
Received cmd data 0x22 (0x3), length: 92
Cmd response seq 3 func 0x22 (0x3)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x22 (0x3)
depth camera intrinsic parameters: fx 365.010315, fy 365.010315, cx 259.066986, cy 207.043594
depth camera radial distortion coeffs: k1 0.092289, k2 -0.273054, p1 0.000000, p2 0.000000, k3 0.098222

===

Cmd seq 4 func 0x22 (0x2)
Cmd sent, 24 bytes sent
Cmd response seq 4 func 0x22 (0x2)
Cmd response success, 1302882 bytes received
Received cmd data 0x22 (0x2), length: 1302882
Cmd response seq 4 func 0x22 (0x2)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x22 (0x2)

===

Cmd seq 5 func 0x22 (0x4)
Cmd sent, 24 bytes sent
Cmd response seq 5 func 0x22 (0x4)
Cmd response success, 12981 bytes received
Received cmd data 0x22 (0x4), length: 12981
Cmd response seq 5 func 0x22 (0x4)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x22 (0x4)
1081.37
959.5
539.5
863
52
0.000412203
-3.32267e-05
-1.03431e-06
0.000261537
-0.00106513
-2.11046e-05
0.000270872
0.636668
0.00113992
0.0997265
-3.66343e-05
0.000620034
0.000350574
-3.57244e-05
-5.83431e-05
5.10673e-05
-0.0010234
-0.0011634
0.635936
0.0197555

===

Cmd seq 6 func 0x16 (0x90000)
Cmd sent, 24 bytes sent
Cmd response seq 6 func 0x16 (0x90000)
Cmd response success, 4 bytes received
Received cmd data 0x16 (0x90000), length: 4
Cmd response seq 6 func 0x16 (0x90000)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x16 (0x90000)
Received status KCMD_READ_STATUS (0x90000): 9729

===

Cmd seq 7 func 0x09 (0)
Cmd sent, 20 bytes sent
Cmd response seq 7 func 0x09 (0)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x09 (0)
Setting stream status: Enable

===

Cmd seq 8 func 0x16 (0x90000)
Cmd sent, 24 bytes sent
Cmd response seq 8 func 0x16 (0x90000)
Cmd response success, 4 bytes received
Received cmd data 0x16 (0x90000), length: 4
Cmd response seq 8 func 0x16 (0x90000)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x16 (0x90000)
Received status KCMD_READ_STATUS (0x90000): 9759

===

Cmd seq 9 func 0x2b (0x1)
Cmd sent, 24 bytes sent
Cmd response seq 9 func 0x2b (0x1)
Cmd response success, 16 bytes received
Cmd response completed
Response complete for cmd 0x2b (0x1)
Set stream status success: Enable
             speed: 5000 Mbit/s (USB SuperSpeed)
[DepthPacketStreamParser::handleNewData] not all subsequences received 0
[DepthPacketStreamParser::handleNewData] not all subsequences received 1022
[CpuDepthPacketProcessor] avg. time: 45.6515ms -> ~21.9051Hz
[CpuDepthPacketProcessor] avg. time: 46.5951ms -> ~21.4615Hz
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 3
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 3
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 3
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 3
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 3
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 3
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 3
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 3
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 3
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1

libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1

[TransferPool::submit] transfer submission disabled!
libusbx: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 1
[TransferPool::submit] transfer submission disabled!
closing kinect...
[TransferPool::submit] transfer submission disabled!Setting sensor status: Disable

[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
Releasing interface 0...
Releasing interface 1...
Closing device...
libusbx: warning [libusb_exit] application left some devices open

**Comment by ofTheo** [comment]
should be fixed by latest commits!
