### ISSUE TITLE
exc_bad_access when trying to use ofVboMesh

### ISSUE THREAD

**Issue by eighteight** [ofTheo/ofxKinectV2#6]
I am trying to go through a usual route of displaying pointclouds using VBOs. After adding a simple "depth pixels" -> VBO code, I started getting exc_bad_access at glDrawArrays line below:

![screen shot 2014-09-01 at 9 37 03 pm](https://cloud.githubusercontent.com/assets/542368/4113018/bc88677c-3241-11e4-9c31-c85116aea6a1.png)

My first thought was that I am not setting the VBOs correctly, and to test that idea, I set the vbo WITHOUT using kinect data, lifted from the openframeworks' pointCloudExample, whereby the VBO is set from a static image. However, even in that case the code breaks in the same way.

That proves that setting the VBOs from kinect depth data is not an issue. 

Furthermore, if I eliminate both        
     texDepth->loadData( kinect.getDepthPixels() );
     texRGB.loadData( kinect.getRgbPixels() );

in update method, the problem goes away.

I think there might be a memory problem with the kinect data, which exhibits itself when it loads into textures.

The code I am using is below:

     #include "ofApp.h"
     #define DEPTH_WIDTH 512
     #define DEPTH_HEIGHT 424
     //--------------------------------------------------------------
     void ofApp::setup(){
         if( !ofFile::doesFileExist("11to16.bin") ){
             ofSystemAlertDialog("Make sure you have 11to16.bin, xTable.bin and zTable.bin in your data      folder!");
        ofExit(); 
         }

    ofBackground(30, 30, 30);

    panel.setup("distance in mm", "settings.xml", 540, 100);
    panel.add(kinect.minDistance);
    panel.add(kinect.maxDistance);

	panel.setPosition(ofPoint(10,10));
	panel.add(noiseAmount.setup("Noise Amount", 0.0, 0.0,20.0));
	panel.add(pointSkip.setup("Point Skip", 1, 1,20));
	panel.add(useRealColors.setup("Real Colors", false));
	panel.add(colorAlpha.setup("Color Alpha", 255,0,255));
	showGui = true;
    panel.loadFromFile("settings.xml");

    kinect.open();
    ////////
    // fx
	postFx.init(ofGetWidth(), ofGetHeight());
	
	postFx.createPass<BloomPass>();
	postFx.createPass<FxaaPass>();
    
    pointSkip = 40;
    
    syphonServerRGB.setName("kinectRGB");
    syphonServerDepth.setName("kinectDepth");
    
    isSaving = false;
    
     pointSize = 3;
    
    
    ///
    
    // load an image from disk
	img.loadImage("linzer.png");
	
	// we're going to load a ton of points into an ofMesh
	vbomesh.setMode(OF_PRIMITIVE_POINTS);
	
	// loop through the image in the x and y axes
	int skip = 4; // load a subset of the points
	for(int y = 0; y < img.getHeight(); y += skip) {
		for(int x = 0; x < img.getWidth(); x += skip) {
			ofColor cur = img.getColor(x, y);
			if(cur.a > 0) {
				// the alpha value encodes depth, let's remap it to a good depth range
				float z = ofMap(cur.a, 0, 255, -300, 300);
				cur.a = 255;
				vbomesh.addColor(cur);
				ofVec3f pos(x, y, z);
				vbomesh.addVertex(pos);
			}
		}
	}
    
	ofEnableDepthTest();
	glEnable(GL_POINT_SMOOTH); // use circular points instead of square points
	glPointSize(3); // make the points bigger
  

    //here I am trying to allocate texture on heap --- this has no effect.  
    texDepth = new ofTexture();

  
     }

     //--------------------------------------------------------------
     void ofApp::update(){
    kinect.update();
    if( kinect.isFrameNew() ){
        texDepth->loadData( kinect.getDepthPixels() );
        texRGB.loadData( kinect.getRgbPixels() );
     //        //ofMesh mesh;
     //        vbomesh.clear();
     //        vbomesh.setMode(OF_PRIMITIVE_POINTS);
     //
     //		int skpDepth = 4;
     //		for(int x=0; x < DEPTH_WIDTH; x+=skpDepth) {
     //			for(int y=0; y < DEPTH_HEIGHT; y+=skpDepth) {
     //				float distance = kinect.getDepthPixels()[y * DEPTH_WIDTH + x]; //        getDistanceAt(x, y);
     //                
     //				if(distance > 100. && distance < 1100) {
     //					vbomesh.addVertex(ofVec3f(x, y, distance));
     //				}
     //			}
     //		}
    }
     }

    //--------------------------------------------------------------
    void ofApp::draw(){
    //    texDepth.draw(10, 100);
    //    texRGB.draw(10, 110 + texDepth.getHeight(), 1920/4, 1080/4);
    
    if (texRGB.isAllocated()) {
        syphonServerRGB.publishTexture(&texRGB);
    }
    
    if (texDepth->isAllocated()){
        syphonServerDepth.publishTexture(texDepth);
    }
    
    
    ofSetColor(255, 255, 255);
    
    easyCam.begin();
    drawPointCloud();
    easyCam.end();
    
	// draw instructions
	ofSetColor(255, 255, 255);
	stringstream reportStream;
	reportStream
    << "fps: " << ofGetFrameRate() << endl
	<< "step = " << step << endl
    << "pointSize = " << pointSize << endl;
	ofDrawBitmapString(reportStream.str(),20,20);
    }

     void ofApp::exit(){
    delete texDepth;
     }
     void ofApp::drawPointCloud() {
     //    if (!texDepth.isAllocated()) return;
    
	ofVboMesh mesh;
	mesh.setMode(OF_PRIMITIVE_POINTS);
	int step = 4;
	for(int y = 0; y < DEPTH_HEIGHT; y += step) {
		for(int x = 0; x < DEPTH_WIDTH; x += step) {
            float distance = 10.0;//kinect.getDepthPixels()[y * DEPTH_WIDTH + x];
			if(distance > 0. && distance < 10000) {
				//mesh.addColor(kinect.getColorAt(x,y));
				mesh.addVertex(ofVec3f(x,y,distance));
			}
		}
	}
	glPointSize(2);
	ofPushMatrix();
	// the projected points are 'upside down' and 'backwards'
	ofScale(1, -1, -1);
	//ofTranslate(0, 0, -1000); // center the points a bit
	ofEnableDepthTest();
    //texDepth.bind();
    if (vbomesh.getNumVertices() > 0)
        vbomesh.draw();
	ofDisableDepthTest();
	ofPopMatrix();
    
     }

     void ofApp::drawPointCloud1() {
    if (!texDepth->isAllocated()) return;
    
	ofMesh mesh;
	mesh.setMode(OF_PRIMITIVE_POINTS);
	int step = 4;
	for(int y = 0; y < DEPTH_HEIGHT; y += step) {
		for(int x = 0; x < DEPTH_WIDTH; x += step) {
            float distance = kinect.getDepthPixels()[y * DEPTH_WIDTH + x];
			if(distance > 0 && distance < 10000) {
				//mesh.addColor(kinect.getColorAt(x,y));
				mesh.addVertex(ofVec3f(x,y,distance));
			}
		}
	}
	glPointSize(2);
	ofPushMatrix();
	// the projected points are 'upside down' and 'backwards'
	ofScale(1, -1, -1);
	//ofTranslate(0, 0, -1000); // center the points a bit
	ofEnableDepthTest();
	mesh.drawVertices();
	ofDisableDepthTest();
	ofPopMatrix();
    
     }

     //--------------------------------------------------------------
     void ofApp::keyPressed(int key){
    
    if (key == 's'){
        isSaving = !isSaving;
    }

     }

     //--------------------------------------------------------------
     void ofApp::keyReleased(int key){

     }

     //--------------------------------------------------------------
     void ofApp::mouseMoved(int x, int y ){

     }

     //--------------------------------------------------------------
     void ofApp::mouseDragged(int x, int y, int button){

     }

     //--------------------------------------------------------------
     void ofApp::mousePressed(int x, int y, int button){

     }

     //--------------------------------------------------------------
     void ofApp::mouseReleased(int x, int y, int button){

     }

     //--------------------------------------------------------------
     void ofApp::windowResized(int w, int h){

     }

     //--------------------------------------------------------------
     void ofApp::gotMessage(ofMessage msg){

     }

     //--------------------------------------------------------------
     void ofApp::dragEvent(ofDragInfo dragInfo){ 

     }

**Comment by ofTheo** [comment]
hmm - it might be needing a deep copy vs a shallow copy of the data. 
could you try with the latest master and see if the issue remains?
