### ISSUE TITLE
flash Kinect firmware

### ISSUE THREAD

**Issue by frannyglass79** [ofTheo/ofxKinectV2#7]
Hi,

the readme says "Kinect needs to have flashed firmware ( this currently needs to be done on Windows 8 )". But I cant find any information on how to do that.

Any pointers?

Thanks
Nadja

**Comment by rootux** [comment]
Is this still relevant. I have the SDK but I don't see anywhere I need to flash my device. The demo apps are running well. It's a kinect windows v2 device
